# Generated by Django 4.0.5 on 2022-06-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_review', '0002_remove_songreview_user_remove_album_external_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumreview',
            name='albumArtists',
        ),
        migrations.RemoveField(
            model_name='albumreview',
            name='albumId',
        ),
        migrations.RemoveField(
            model_name='albumreview',
            name='albumTitle',
        ),
        migrations.RemoveField(
            model_name='albumreview',
            name='image',
        ),
        migrations.RemoveField(
            model_name='albumreview',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='albumreview',
            name='review',
        ),
        migrations.RemoveField(
            model_name='albumreview',
            name='time',
        ),
        migrations.RemoveField(
            model_name='albumreview',
            name='user',
        ),
        migrations.AddField(
            model_name='albumreview',
            name='author',
            field=models.CharField(default='No Author', max_length=100),
        ),
        migrations.AddField(
            model_name='albumreview',
            name='content',
            field=models.CharField(default='No Content', max_length=255),
        ),
        migrations.AddField(
            model_name='albumreview',
            name='title',
            field=models.CharField(default='No Title', max_length=255),
        ),
    ]
